# Generated by Django 5.1.3 on 2024-11-25 10:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PreSessionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("coach_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                ("weight", models.FloatField()),
                (
                    "sleep",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "soreness",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "mental_stress",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "fatigue",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "pain_scale",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "stiffness",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                ("grip_strength", models.FloatField()),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("Strength", "Strength"),
                            ("Power", "Power"),
                            ("Endurance", "Endurance"),
                            ("Track", "Track"),
                            ("Boxing", "Boxing"),
                            ("Rehab", "Rehab"),
                            ("Conjugate", "Conjugate"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "sub_session_type",
                    models.CharField(
                        choices=[
                            ("Upper Body", "Upper Body"),
                            ("Lower Body", "Lower Body"),
                            ("Full Body", "Full Body"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PostSessionMetrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_name", models.CharField(max_length=100)),
                ("date", models.DateField()),
                (
                    "rpe",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "pain_scale",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "session_duration",
                    models.IntegerField(
                        help_text="Enter session duration in minutes only.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "pre_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_sessions",
                        to="well_tracker.presessionmetrics",
                    ),
                ),
            ],
        ),
    ]
