# Generated by Django 5.1.3 on 2024-11-28 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="postsessionmetrics",
            name="pre_session",
        ),
        migrations.RemoveField(
            model_name="presessionmetrics",
            name="session_type",
        ),
        migrations.RemoveField(
            model_name="presessionmetrics",
            name="sub_session_type",
        ),
        migrations.AddField(
            model_name="postsessionmetrics",
            name="avg_HR",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="fatigue",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="mental_stress",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="pain_scale",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="sleep",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="soreness",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="stiffness",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ]
            ),
        ),
    ]
