# Generated by Django 5.1.3 on 2024-11-28 11:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0002_remove_postsessionmetrics_pre_session_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presessionmetrics",
            name="composite_score",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
