# Generated by Django 5.1.3 on 2024-12-01 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0003_presessionmetrics_composite_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postsessionmetrics",
            name="acwr_HR",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="postsessionmetrics",
            name="acwr_rpe",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
