# Generated by Django 5.1.3 on 2024-12-01 07:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0004_postsessionmetrics_acwr_hr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postsessionmetrics",
            name="coach_name",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_HR",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_rpe",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
