# Generated by Django 5.1.3 on 2024-12-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0005_postsessionmetrics_coach_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_HR",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_rpe",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
