# Generated by Django 5.1.3 on 2024-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0006_alter_postsessionmetrics_acwr_hr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_HR",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="acwr_rpe",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="postsessionmetrics",
            name="avg_HR",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="grip_strength",
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="weight",
            field=models.FloatField(default=0),
        ),
    ]
