# Generated by Django 5.1.3 on 2024-12-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0007_alter_postsessionmetrics_acwr_hr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presessionmetrics",
            name="rhr",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="presessionmetrics",
            name="sleep_quantity",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="presessionmetrics",
            name="grip_strength",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
