# Generated by Django 5.1.3 on 2024-12-07 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("well_tracker", "0008_presessionmetrics_rhr_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presessionmetrics",
            name="weight",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
