# Generated by Django 5.1.4 on 2024-12-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('well_tracker', '0010_alter_postsessionmetrics_avg_hr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsessionmetrics',
            name='session_duration',
            field=models.IntegerField(),
        ),
    ]
